name: Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.2'
          bundler-cache: true

      - run: bundle install

      - run: bundle exec rspec

      - run: bundle exec rubocop
